server:
  port: 8080
  servlet:
    context-path: /GreenCare

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/GreenCareTest"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
